### ISSUE TITLE
Submit new task using [enter]

### ISSUE THREAD

**Issue by marcvangend** [dmsmidt/redmine-plus#1]
To be able to work faster (especially when creating lots of tasks) I'd like to submit the 'new task' form on a taskboard when pressing the [enter] key. Currently the options are to tab multiple times until you reach the [OK] button, or reach for your mouse and click. Of course, when the focus is on a textarea, the expected behavior should be a new line, not a form submit.

**Comment by dmsmidt** [comment]
This is fixed in 0.11.4.

You can now use Ctrl + Enter
